os:
 - linux
language: cpp
branches:
  only:
    - master
    - travis-ci-thoro
    - travis-ci-build-test
    - coverity_scan
matrix:
  include:
    - os: linux
      env:
        ANALYZE="scan-build-3.6 --use-cc clang-3.6 --use-c++ clang++-3.6 "
      compiler: clang
  allow_failures:
    - env: ANALYZE="scan-build-3.6 --use-cc clang-3.6 --use-c++ clang++-3.6 "

before_install:
 - ./CI/before_install.linux.sh
before_script:
 - ./CI/before_script.linux.sh
script:
 - cd ./build
 - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then ${ANALYZE}make -j4; fi
 - if [ "$COVERITY_SCAN_BRANCH" != 1 ] && [ "${TRAVIS_OS_NAME}" = "osx" ]; then make package; fi
after_script:
 - ./openmw_test_suite
notifications:
  email: false
